name: graficacion_ai
description: "Una app de graficación matemática 2D/3D con asistencia de IA."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  http: ^1.2.0

  # --- Iconos base ---
  cupertino_icons: ^1.0.6

  # --- Gestión de Estado ---
  provider: ^6.1.1

  # --- Matemáticas y Lógica ---
  math_expressions: ^3.1.0
  vector_math: ^2.1.4

  # --- Visualización (Gráficos) ---
  fl_chart: ^1.1.1
  
  # 3D con ditredi (se sigue usando como fallback si quieres)
  ditredi: ^2.0.2

  # 3D mejorado: WebView para Three.js (WebGL real)
  webview_flutter: ^4.13.0

  # --- Inteligencia Artificial ---
  google_generative_ai: ^0.4.6
  
  # --- UI / Diseño ---
  flutter_markdown: ^0.7.7+1
  flutter_markdown_latex: any
  markdown: any
  google_fonts: ^8.0.1
  flutter_dotenv: ^5.1.0

  # --- Firebase ---
  firebase_core: ^2.27.2
  firebase_auth: ^4.18.0
  cloud_firestore: ^4.15.10
  image_picker: ^1.2.1
  firebase_storage: ^11.7.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - .env